In [8]:
#IMPORTS
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics,neighbors,svm
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [9]:

data=pd.read_csv('car.data')
data.columns = ['Buying', 'maint', 'doors', 'persons', 'lug_boots', 'safety', 'condition']

print(data.head())


  Buying  maint doors persons lug_boots safety condition
0  vhigh  vhigh     2       2     small    med     unacc
1  vhigh  vhigh     2       2     small   high     unacc
2  vhigh  vhigh     2       2       med    low     unacc
3  vhigh  vhigh     2       2       med    med     unacc
4  vhigh  vhigh     2       2       med   high     unacc


In [14]:
#data preprocessing
x=data[['Buying','maint','doors','persons','lug_boots','safety']].values
y=data[['condition']]
le=LabelEncoder()
for i in range(len(x[0])):
    x[:,i]=le.fit_transform(x[:,i])
print(x)

maping={'unacc':0,'acc':1,'good':2,'vgood':3}
y['condition']=y['condition'].map(maping)
y=np.array(y)
print(y)

[[3 3 0 0 2 2]
 [3 3 0 0 2 0]
 [3 3 0 0 1 1]
 ...
 [1 1 3 2 0 1]
 [1 1 3 2 0 2]
 [1 1 3 2 0 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


<ipython-input-14-d38682404039>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['condition']=y['condition'].map(maping)


In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [16]:
#KNN
KNN=neighbors.KNeighborsClassifier(n_neighbors=10,weights='uniform')
KNN.fit(x_train,y_train)
prediction=KNN.predict(x_test)
accuracy=metrics.accuracy_score(y_test,prediction)
print("prediction: ",prediction)
print("accuracy: ",accuracy*100,"%")


prediction:  [0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 3 0 0 0 0 0 0 2 0 0 1 0 0 0 0 0 0 0
 1 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0
 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 3
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 3 3 0
 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 1 0 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 2 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 3 1 0 0
 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 3 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 3 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 3 0 0 1 0 0 0 0 0 0 0
 0 0 0 1 1 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1
 0 0 2 0 0 0

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [17]:
#SVM
SVM=svm.SVC()
SVM.fit(x_train,y_train)
prediction=SVM.predict(x_test)
accuracy=metrics.accuracy_score(y_test,prediction)
print("prediction: ",prediction)
print("accuracy: ",accuracy*100,"%")

prediction:  [0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 1 1 0 3 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0
 1 0 0 0 0 3 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 3 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 0 1 1 0 0 0 3 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 3
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 0 1 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 3 1 0 0 0 1 0 1 0 1 3 3 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 3 1 0 1 0
 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 3 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 2 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 3 1 0 0
 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 3 1 3 0 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 3 0 0 0 0 3 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 3 1 1 3 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 3 1 0 0 1 0 0 0 0 3 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 2 0
 0 0 2 0 1 0

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
